/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database_console;

import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Guilherme
 */
public class AvaliarFilme extends javax.swing.JFrame {

    public String usuario;
    
    String host = "jdbc:postgresql://localhost:5432/postgres";  //endereco da conexao do banco de dados
    String user = "postgres";                                   //usuario
    String pass = "postgres";                                   //senha
    
    /**
     * Creates new form AvaliarFilme
     */
    public AvaliarFilme(String usuario) {
        initComponents();
        this.usuario = usuario;
    }

    private void popAviso(String in) {
        JFrame frame = new JFrame();
        JOptionPane.showMessageDialog(frame, in);
        return;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        botaoVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        campoBusca1 = new javax.swing.JTextField();
        botao1 = new javax.swing.JRadioButton();
        botao2 = new javax.swing.JRadioButton();
        botao3 = new javax.swing.JRadioButton();
        botao4 = new javax.swing.JRadioButton();
        botao5 = new javax.swing.JRadioButton();
        botaoEnviar = new javax.swing.JButton();
        botao0 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botaoVoltar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nome do Filme:");

        campoBusca1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        buttonGroup1.add(botao1);
        botao1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao1.setText("*");
        botao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(botao2);
        botao2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao2.setText("**");

        buttonGroup1.add(botao3);
        botao3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao3.setText("***");

        buttonGroup1.add(botao4);
        botao4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao4.setText("****");

        buttonGroup1.add(botao5);
        botao5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botao5.setText("*****");

        botaoEnviar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoEnviar.setText("Enviar");
        botaoEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnviarActionPerformed(evt);
            }
        });

        buttonGroup1.add(botao0);
        botao0.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Quantas estrelas você dá para o filme?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoBusca1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botaoEnviar)
                                    .addComponent(botao3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botao0)
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(botao1)
                                            .addComponent(botao4))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botao5)
                                    .addComponent(botao2)
                                    .addComponent(botaoVoltar)))
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoBusca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botao0)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botao1)
                        .addComponent(botao2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao4)
                    .addComponent(botao5)
                    .addComponent(botao3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoVoltar)
                    .addComponent(botaoEnviar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        JFrame janela = new Selecao(usuario);
        janela.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao1ActionPerformed

    private void botaoEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEnviarActionPerformed
        String input, busca;
        int estrelas;
        busca = campoBusca1.getText().toUpperCase();
        if (botao1.isSelected()) {      //verifica qual botao foi apertado
            estrelas = 1;
        } else if (botao0.isSelected()) {
            estrelas = 0;
        } else if (botao2.isSelected()) {
            estrelas = 2;
        } else if (botao3.isSelected()) {
            estrelas = 3;
        } else if (botao4.isSelected()) {
            estrelas = 4;
        } else if (botao5.isSelected()) {
            estrelas = 5;
        } else {
            popAviso("Por favor selecione uma avaliação.");
            return;
        }
        input = "SELECT IDFILME,TITULO,USUARIO FROM CLASSIFICA C, FILME F "
                + "WHERE C.FILME = F.IDFILME AND "
                + "upper(C.USUARIO) = upper('" + usuario + "') AND "
                + "upper(F.TITULO) = '"+busca.toUpperCase()+"'"; 
        //procura por uma avaliacao já feita na tabela classifica
        try {
            //realizar o carregamento do JDBC
            Class.forName("org.postgresql.Driver");
            //construindo a conexão com o SGBD PostgreSQL
            Connection conexao = DriverManager.getConnection(host, user, pass);

            PreparedStatement instrucao = conexao.prepareStatement(input);
            //executa a sql parametrizada em "instrucao"
            ResultSet result = instrucao.executeQuery(); //recebe os resultados da query
            int count = 0;
            while (result.next()) count++;
            if (count == 0) { //caso não exista uma avaliação, busca na tabela de filmes se o filme existe
                input = "SELECT idfilme FROM FILME F WHERE upper(F.TITULO) = '"
                        + busca.toUpperCase() + "'";
                instrucao = conexao.prepareStatement(input);
                result = instrucao.executeQuery();      //reposiciona ponteiro de leitura dos resultados
                while (result.next()) {
                    count++;
                }
                if (count == 0) {
                    popAviso("Filme inexistente!");
                    return;
                } else {
                    result = instrucao.executeQuery();
                    result.next();
                    int filme = result.getInt("idfilme");   //pega a ID do filme, caso exista
                    input = "INSERT INTO CLASSIFICA VALUES ('"
                            + usuario + "','" + filme + "','" + estrelas + "')";
                    instrucao = conexao.prepareStatement(input);
                    instrucao.executeUpdate();
                    popAviso("Avaliação feita com sucesso!");
                }
            } else {
                result = instrucao.executeQuery();
                result.next();
                int filme = result.getInt("IDFILME");   //pega a ID do filme, caso exista
                input = "UPDATE CLASSIFICA SET estrelas=('"+estrelas+
                        "') WHERE upper(USUARIO)='"+usuario.toUpperCase()+"' AND FILME = '"
                        + filme +"'";
                instrucao = conexao.prepareStatement(input);
                instrucao.executeUpdate();
                popAviso("Avaliação feita com sucesso!");
            }
            result.close();       //encerra a consulta
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "ERRO CLASSE: " + e.getMessage());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERRO SQL: " + e.getMessage());
        }
    }//GEN-LAST:event_botaoEnviarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botao0;
    private javax.swing.JRadioButton botao1;
    private javax.swing.JRadioButton botao2;
    private javax.swing.JRadioButton botao3;
    private javax.swing.JRadioButton botao4;
    private javax.swing.JRadioButton botao5;
    private javax.swing.JButton botaoEnviar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField campoBusca1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
