/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package database_console;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Guilherme
 */
public class UserExist extends javax.swing.JFrame {
    
    String host = "jdbc:postgresql://localhost:5432/postgres";  //endereco da conexao do banco de dados
    String user = "postgres";                                   //usuario
    String pass = "postgres";                                   //senha
    
    /**
     * Creates new form UserExist
     */
    public UserExist() {
        initComponents();
    }
        private void popAviso(String in) {
        JFrame frame = new JFrame();
        JOptionPane.showMessageDialog(frame, in);
        return;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nome de Usuário");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jButton1)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            //realizar o crregamento do jdbc
            Class.forName("org.postgresql.Driver");
            //construindo a conexão com o sgbd postgresql
            Connection conexao = DriverManager.getConnection(host, user, pass);
            //CONSTRUCAO DA CLASSE PREPAREDSTATEMENT PARA PASSAGEM DE PARAMETROS
            PreparedStatement instrucao = conexao.prepareStatement("SELECT username FROM usuario WHERE username = ?");
            instrucao.setString(1, jTextField1.getText());
            //executando a sql parametrizada
            ResultSet result = instrucao.executeQuery();
            int count = 0;
            while(result.next()) count++;
            if(count == 0){
                popAviso("Usuário não existente!");
                PrimeiraTela tela = new PrimeiraTela();
                tela.setVisible(true);
                dispose();
                return;
            }
            result = instrucao.executeQuery();//reposiciona ponteiro de leitura dos resultados
            result.next();
            if(result.getString("username").compareToIgnoreCase(jTextField1.getText()) == 0){
                user = jTextField1.getText();
            }
            JOptionPane.showMessageDialog(null, "Login Efetuado");
            JFrame janela = new Selecao(user);
            janela.setVisible(true);
            dispose();
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Erro Classe: " + e.getMessage());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro SQL: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
